JASSETS-55 migration of code from another repo
qubistlabs/jassets-admin pull request #1
Opened 2019-09-02 08:27 UTC by deftonee

2019-09-02 08:42 UTC, romantolkachyov reviewed
Поправь форматирование. Лучше сразу добавить Dockerfile и Jenkinsfile по крайней мере с линтерами (см. репу jassets).

2019-09-02 08:42 UTC, romantolkachyov commented on jassets_admin/admin.py
> +    list_display = ('id', 'uuid', 'name', 'description', 'platform_obj',
Это лучше на отдельные строки разбить: последующие изменения списка станут более читабельными и проще понять кто их внёс по blame.

2019-09-02 08:43 UTC, romantolkachyov commented on jassets_admin/settings.py
> +        'NAME': 'jassets',
Эти значения нужно подхватить из env-ов. Так же в `default` нужно заюзать postgres и конфигурировать из окружения (текущие значения можно оставить дефолтными).

2019-09-02 09:21 UTC, pohmelie approved these changes

2019-09-03 10:40 UTC, uliantsev-a commented on run.sh
> +    export ADMIN_PASSWORD='admin'
Я бы не добавлял в ветку логины и пароли, можно в Readme написать пример использования .env или export.

2019-09-03 10:42 UTC, uliantsev-a commented on run.sh
> +    python manage.py shell < init_db.py
Это обычный сценарий запуска приложения и каждый раз будет пытаться создавать юзера. Может лучше вынести init_db в `"${RUNMODE}" = "init"`?

2019-09-03 10:48 UTC, uliantsev-a commented on init_db.py
> +    User.objects.create_superuser(
1. Почему встроеный в Django сценарий `manage.py createsuperuser` не подошел или в будущем более сложная логика создания юзера планируется?

2019-09-03 10:49 UTC, uliantsev-a approved these changes

2019-09-03 10:51 UTC, uliantsev-a commented on init_db.py
> +    User.objects.create_superuser(
2. Насколько понимаю скрипт актуален при первом запуске, есть ли нужда в переменных окружениях а не диалога как в том же `manage.py createsuperuser`

2019-09-03 12:27 UTC, romantolkachyov commented on run.sh
> +    export ADMIN_PASSWORD='admin'
Env-ы нужно прописать в `docker-compose.yml`. Секретные ключи (sentry, допустим) в `docker-compose.override.yml` добавит каждый разработчик сам, но желательно сделать их опциональными, либо описать в `docker-compose.override.yml.example`.

2019-09-03 12:29 UTC, romantolkachyov commented on run.sh
> +    python manage.py shell < init_db.py
Можно пока вообще выкинуть `init_db.py`. В остальных проектах мы это руками делаем.

2019-09-03 12:36 UTC, deftonee commented on init_db.py
> +    User.objects.create_superuser(
createsuperuser подходит, но не для запуска через докер. Я пробовал через скрипт для докера послать ему пароль через `yes 1 1 | ./manage.py createsuperuser --username admin --email ""` но там выходит ошибка. Поэтому решил таким способом создать.

2019-09-03 12:37 UTC, deftonee commented on run.sh
> +    python manage.py shell < init_db.py
Попробую. Спасибо

2019-09-03 12:38 UTC, deftonee commented on run.sh
> +    export ADMIN_PASSWORD='admin'
Понял. Переделаю

2019-09-03 16:48 UTC, romantolkachyov approved these changes

2019-09-03 16:48 UTC, romantolkachyov commented on jassets_admin/routers.py
> +
Хорошо бы тут докстринг добавить. Описать для чего роутер заюзан.

2019-09-03 16:48 UTC, romantolkachyov commented on jassets_admin/settings.py
> +    'jassets': {
@bizywizy нам есть смысл связываться с multi db?) Или лучше согласиться на то, что в базе jassets будут лежать таблички jassets-admin?

2019-09-04 09:43 UTC, bizywizy requested changes
Надо с чойсами что-то решить (если все работает и я ошибаюсь, то дай знать) и обязательно SECRET_KEY вынести в переменные окружения

2019-09-04 09:43 UTC, bizywizy commented on jassets_admin/settings.py
> +SECRET_KEY = '2t=j)t6-7lknd_xa_gs3@56nt4mi_f7%yy*24q*owc*5sfm#ne'
Вот это в ENV бы

2019-09-04 09:43 UTC, bizywizy commented on jassets_admin/enums.py
> +        return tuple((i.name, i.name) for i in cls)
Тут точно должно быть `(i.name, i.name)`, `.value` тебе не нужно?

2019-09-04 09:43 UTC, bizywizy commented on jassets_admin/models.py
> +    type = models.CharField(max_length=50, choices=AssetType.choices())
Насколько я помню, `Asset.objects.filter(type=AssetType.FIAT)` будет приводить AssetType.FIAT к строке:
```
>>>str(AssetType.FIAT)
>>>'AssetType.FIAT'
```
что при твоих чойсах не найдет ничего

2019-09-04 11:07 UTC, deftonee commented on jassets_admin/enums.py
> +        return tuple((i.name, i.name) for i in cls)
Это для choices в поле модели и автоматической фильтрации через админку.
<img width="914" alt="image" src="https://user-images.githubusercontent.com/7039912/64249859-5f37bb80-cf1d-11e9-8892-5e8a37816e73.png">

2019-09-04 11:12 UTC, deftonee commented on jassets_admin/enums.py
> +        return tuple((i.name, i.name) for i in cls)
Так как в БД значения в таком виде лежат. Например, 'token'

2019-09-04 12:01 UTC, bizywizy commented on jassets_admin/settings.py
> +    'jassets': {
Дв пусть будет несколько БД, пока еще не было особых проблем с этим, роутер все решает

2019-09-04 12:01 UTC, bizywizy commented on jassets_admin/enums.py
> +        return tuple((i.name, i.name) for i in cls)
Как скажешь)

2019-09-04 14:51 UTC, deftonee commented on jassets_admin/models.py
> +    type = models.CharField(max_length=50, choices=AssetType.choices())
Действительно есть такая проблема. Переделал значения энама на капсовые, чтобы их можно было использовать в запросах. Таким образом придется писать запросы так: `Asset.objects.filter(type=AssetType.COIN.name)` или так `Asset.objects.filter(type=AssetType.COIN.value)`

2019-09-04 14:52 UTC, deftonee commented on jassets_admin/routers.py
> +
Описал

2019-09-04 14:52 UTC, deftonee commented on jassets_admin/settings.py
> +SECRET_KEY = '2t=j)t6-7lknd_xa_gs3@56nt4mi_f7%yy*24q*owc*5sfm#ne'
Вынес

2019-09-04 15:26 UTC, bizywizy commented on jassets_admin/models.py
> +    type = models.CharField(max_length=50, choices=AssetType.choices())
Вообще на раздумие можно оставить стоит ли енамы юзать в чойсах или нет, вроде красиво, а вроде и нет)

2019-09-04 15:27 UTC, bizywizy approved these changes

2019-09-04 17:13 UTC, deftonee commented
@romantolkachyov, все аппрувы получены. Уже можно мержить?

2019-09-04 17:41 UTC, romantolkachyov commented
Да, теперь точно)

2019-09-04 18:56 UTC, merged